# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/fifo_gen/fifo_gen.xci
# IP: The module: 'fifo_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/fifo_gen/fifo_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/fifo_gen/fifo_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/fifo_gen/fifo_gen.xci
# IP: The module: 'fifo_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/fifo_gen/fifo_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/fifo_gen/fifo_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
