# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_processing_system7_0_0/BlockDesign_processing_system7_0_0.xci
# IP: The module: 'BlockDesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_processing_system7_0_0/BlockDesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockDesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_processing_system7_0_0/BlockDesign_processing_system7_0_0.xci
# IP: The module: 'BlockDesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_processing_system7_0_0/BlockDesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockDesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
