# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/axi4stream_vip_0/axi4stream_vip_0.xci
# IP: The module: 'axi4stream_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/axi4stream_vip_0/axi4stream_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4stream_vip_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/axi4stream_vip_0/axi4stream_vip_0.xci
# IP: The module: 'axi4stream_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/QPSKBlock2/QPSKBlock2.srcs/sources_1/ip/axi4stream_vip_0/axi4stream_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4stream_vip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
