# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fifo_gen/fifo_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_gen || ORIG_REF_NAME==fifo_gen} -quiet] -quiet
