# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.cache/wt [current_project]
set_property parent.project_path C:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths c:/VivadoProjects/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_QPSKBlockIP_0_0/src/blk_mem_gen_0/qpsklaginak.coe
read_vhdl -library xil_defaultlib C:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/hdl/BlockDesign_wrapper.vhd
add_files C:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/BlockDesign.bd
set_property used_in_implementation false [get_files -all c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_QPSKBlockIP_0_0/src/fifo_gen/fifo_gen.xdc]
set_property used_in_implementation false [get_files -all c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_QPSKBlockIP_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_HamsterB_0_0/src/hamst_const.xdc]
set_property used_in_implementation false [get_files -all c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_processing_system7_0_0/BlockDesign_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_rst_ps7_0_48M_0/BlockDesign_rst_ps7_0_48M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_rst_ps7_0_48M_0/BlockDesign_rst_ps7_0_48M_0.xdc]
set_property used_in_implementation false [get_files -all c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_rst_ps7_0_48M_0/BlockDesign_rst_ps7_0_48M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/ip/BlockDesign_auto_pc_0/BlockDesign_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/VivadoProjects/ZynqQPSK_System/ZynqQPSK_System.srcs/sources_1/bd/BlockDesign/BlockDesign_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/VivadoProjects/ZynqQPSK_System/hamst_const.xdc
set_property used_in_implementation false [get_files C:/VivadoProjects/ZynqQPSK_System/hamst_const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top BlockDesign_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BlockDesign_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file BlockDesign_wrapper_utilization_synth.rpt -pb BlockDesign_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
