# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/VivadoProjects/ZynqQPSK_System/hamst_const.xdc

# Block Designs: bd/BlockDesign/BlockDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesign || ORIG_REF_NAME==BlockDesign} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_QPSKBlockIP_0_0/BlockDesign_QPSKBlockIP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesign_QPSKBlockIP_0_0 || ORIG_REF_NAME==BlockDesign_QPSKBlockIP_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_HamsterB_0_0/BlockDesign_HamsterB_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesign_HamsterB_0_0 || ORIG_REF_NAME==BlockDesign_HamsterB_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_processing_system7_0_0/BlockDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesign_processing_system7_0_0 || ORIG_REF_NAME==BlockDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_ps7_0_axi_periph_0/BlockDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==BlockDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_rst_ps7_0_48M_0/BlockDesign_rst_ps7_0_48M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesign_rst_ps7_0_48M_0 || ORIG_REF_NAME==BlockDesign_rst_ps7_0_48M_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_auto_pc_0/BlockDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesign_auto_pc_0 || ORIG_REF_NAME==BlockDesign_auto_pc_0} -quiet] -quiet

# XDC: bd/BlockDesign/BlockDesign_ooc.xdc
