# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/usuario/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-2532-DESKTOP-T22LSJU/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/VivadoProjects/project_hamster/project_hamster.cache/wt [current_project]
set_property parent.project_path C:/VivadoProjects/project_hamster/project_hamster.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/VivadoProjects/project_hamster/project_hamster.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/imports/dsp_base_project/i3c2.vhd
  C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/imports/dsp_base_project/adau1761_configuraiton_data.vhd
  C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/imports/dsp_base_project/i2s_data_interface.vhd
  C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/imports/dsp_base_project/i2c.vhd
  C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/imports/dsp_base_project/ADAU1761_interface.vhd
  C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/imports/dsp_base_project/adau1761_izedboard.vhd
  C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/imports/dsp_base_project/adau1761_test.vhd
  C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/new/qpsk_egokitu.vhd
}
add_files C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all C:/VivadoProjects/project_hamster/project_hamster.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/VivadoProjects/project_hamster/project_hamster.srcs/constrs_1/new/hamst_const.xdc
set_property used_in_implementation false [get_files C:/VivadoProjects/project_hamster/project_hamster.srcs/constrs_1/new/hamst_const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top adau1761_test -part xc7z020clg484-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef adau1761_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file adau1761_test_utilization_synth.rpt -pb adau1761_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
